# Site settings
title: USS Quest - Long Beach, CA
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/uss-quest/" # the subpath of your site, e.g. /blog/
url: https://startrekthefleet.github.io/uss-quest/ 
author: Deborah Khider - Copyright &copy; 2025 - Start Bootstrap
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
